name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.7'

    - name: Install Required Packages
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller wmi

    - name: Build Executable GUI
      run: |
        pyinstaller --onefile `
        --add-data "Scripts/datasets/usb.ids:Scripts/datasets" `
        --add-data "Scripts/datasets/pci.ids:Scripts/datasets" `
        HardwareSniffer.py
        mv dist/HardwareSniffer.exe dist/Hardware-Sniffer.exe

    - name: Build Executable CLI
      run: |
        pyinstaller --onefile `
        --add-data "Scripts/datasets/usb.ids:Scripts/datasets" `
        --add-data "Scripts/datasets/pci.ids:Scripts/datasets" `
        Hardware-Sniffer-CLI.py

    - name: Generate Version Number
      id: version
      run: |
        $run_number = [int]$env:GITHUB_RUN_NUMBER + 100
        $major = [math]::floor($run_number / 100)
        $minor = [math]::floor(($run_number % 100) / 10)
        $patch = $run_number % 10
        $version = "$major.$minor.$patch"
        echo "version=$version" >> $env:GITHUB_ENV

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.version }}
        files: |
          ./dist/Hardware-Sniffer.exe
          ./dist/Hardware-Sniffer-CLI.exe
        name: ${{ env.version }}
        body: |
          ## **Changelog**

          - ${{ github.event.head_commit.message }}

          ## **Assets**

          - **Hardware-Sniffer.exe**:
            - A simple executable for quick hardware detection, suited for individual users.

          - **Hardware-Sniffer-CLI.exe**:
            - Command-line interface version designed for seamless integration with OpCore Simplify.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}